name: ðŸ”§ Test and Build

on:
  # Run tests on all pushed branches (includes PR merge)
  push:
    branches: [master]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  test:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@1.1.0
    with:
      image_name: ghcr.io/${{ github.repository }}/service
      build_context: docker
      build_dockerfile: underpass.dockerfile
      compose_service: underpass
      compose_command: wait-for-it postgis:5432 --strict -- "cd /code/build && make check -j `nproc`"
      cache_extra_imgs: |
        "docker.io/postgis/postgis:15-3.3"
    secrets: inherit

  build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.1.0
    with:
      image_name: ghcr.io/${{ github.repository }}/service
      context: docker
      dockerfile: underpass.dockerfile