# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu:kinetic
    # Steps represent a sequence of tasks that will be executed
    # as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your
    # job can access it
    - uses: actions/checkout@v2

    - name: Start Docker Compose
      run: cd docker && docker-compose up -d

    - name: Create Doxyfile
      run: docker-compose -f docker-compose.yml exec -T underpass sh -c "cd /code && ./autogen.sh && ./configure && make docs/Doxyfile -j `nproc`"

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./docs/Doxyfile
          working-directory: .

    - name: Debug
      run: ls -la ./html

    - name: Deploy HTML
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages

  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The docker build workflow failed'
